const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.06});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));

const injected=document.createElement('style');injected.textContent=`
.hero-console{position:relative;overflow:hidden}.hero-console:after{content:"";position:absolute;inset:-35%;background:radial-gradient(circle,rgba(121,199,200,.10),transparent 42%);animation:ambient 9s ease-in-out infinite;pointer-events:none}@keyframes ambient{0%,100%{transform:translate(-12%,-8%)}50%{transform:translate(16%,12%)}}
.hero-status div{transition:.3s}.hero-status div.live{background:rgba(121,199,200,.07);padding-left:9px}.hero-status .gate.live{background:rgba(224,196,142,.07)}
.workspace{transition:box-shadow .35s,transform .35s}.workspace:hover{box-shadow:0 38px 105px rgba(0,0,0,.30)}
.g-node{box-shadow:0 6px 18px rgba(0,0,0,.18)}.g-node:hover{transform:scale(1.12);z-index:9;box-shadow:0 0 24px rgba(121,199,200,.32)}.g-node.selected{outline:2px solid rgba(224,196,142,.65);outline-offset:3px}.g-node.hidden,.g-edge.hidden{opacity:.04;pointer-events:none}.g-edge.path{animation:pathGlow 1.5s ease-in-out infinite alternate}@keyframes pathGlow{from{box-shadow:0 0 4px rgba(224,196,142,.25)}to{box-shadow:0 0 18px rgba(224,196,142,.85)}}
.path-token{position:absolute;width:9px;height:9px;border-radius:50%;background:#f0d6a2;box-shadow:0 0 18px rgba(240,214,162,.9);z-index:7;pointer-events:none;transition:left .55s ease,top .55s ease}
.entity-fact{transition:.25s}.entity-fact:hover{border-color:#60718c;transform:translateY(-2px);background:#101b2b}.source-list button.active{border-color:#8b7449;background:#172132}.lens:hover{color:#f2f1ec}.graph-toolbar button.active{background:#172238}.inspect-badge{display:inline-block;border:1px solid #45566f;border-radius:99px;padding:5px 7px;margin:3px 3px 3px 0;font-size:8px;color:#b9c4d3}.graph-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-top:18px}.graph-stats div{border-top:1px solid #334158;padding-top:8px}.graph-stats small{display:block;color:#718095}.graph-stats b{font-size:11px}.source-inspector{line-height:1.6}
`;document.head.appendChild(injected);

const frames=[['REAL-TIME TRANSACTION MONITORING','A transaction enters PRISM.','Payment context, parties, rail, jurisdiction and source arrive as evidence for evaluation.',['13:42:08.184','INSTANT PAYMENT','USD 8,450','US → US']],['DETECT','Risk becomes visible.','Rules, models and contextual signals identify rapid onward movement and an APP/mule pattern.',['RULE TM-218','BEHAVIOR SIGNAL','APP TYPOLOGY','EVIDENCE 04']],['RESOLVE','Identity fragments converge.','KYC, CRM, payment and investigation records resolve into an evidence-backed canonical entity.',['6 SOURCES','3 ALIASES','1 CANONICAL ENTITY','CONFIDENCE HIGH']],['CONNECT','The entity becomes a network.','Accounts, devices, addresses, companies and counterparties reveal relationships the original alert could not show.',['12+ OBJECTS','TYPED EDGES','SHARED DEVICE','2-HOP PATH']],['AI REASON','PRISM reasons across the evidence.','Transaction, entity, network, chronology and investigation evidence support competing hypotheses and uncertainty.',['HYPOTHESIS H1','HYPOTHESIS H2','EVIDENCE GROUNDED','UNCERTAINTY VISIBLE']],['INVESTIGATE','One connected investigation forms.','Distinct fraud and AML signals retain their controls while shared evidence is assembled in one investigation context.',['FRAUD SIGNAL','AML SIGNAL','COMMON NETWORK','ONE INVESTIGATION']],['RECOMMEND','A next action is proposed.','PRISM recommends escalation and enhanced beneficiary review, with rationale and additional evidence required.',['RECOMMENDATION','RATIONALE','EVIDENCE NEEDED','PROPOSER']],['GOVERN','The flow reaches an authority boundary.','Policy, scope, segregation of duties and four-eyes requirements determine whether the proposal may proceed.',['AUTHORITY CHECK','SCOPE VERIFIED','SOD','FOUR-EYES']],['HUMAN DECIDE','A human remains accountable.','The authorized checker can approve, refuse or request more evidence. The AI cannot invent permission.',['MAKER ≠ CHECKER','APPROVE','REFUSE','AUDITABLE']],['MEASURE','The confirmed outcome changes what PRISM knows.','Outcome, intervention and control effectiveness become attributable measurement and feedback.',['OUTCOME CONFIRMED','EFFECTIVENESS','ATTRIBUTION','FEEDBACK']],['REGULATORY REPORTING','The evidence chain survives to the regulator.','Entity, network, investigation, decision and outcome evidence flow into reportability, review, filing and acknowledgement.',['REPORTABILITY','LINEAGE','HUMAN REVIEW','AUDIT TRAIL']]];
document.querySelectorAll('.journey-step').forEach((b,i)=>b.onclick=()=>{document.querySelectorAll('.journey-step').forEach(x=>x.classList.remove('active'));b.classList.add('active');let f=frames[i];journeyKicker.textContent=f[0];journeyTitle.textContent=f[1];journeyText.textContent=f[2];journeyData.innerHTML=f[3].map(x=>`<span>${x}</span>`).join('')});

const heroStates=[['ENTITY','Resolved'],['NETWORK','Path found'],['AI','Reasoning'],['AUTHORITY','Required']];let heroIx=0;setInterval(()=>{const cards=[...document.querySelectorAll('.hero-status div')];cards.forEach(x=>x.classList.remove('live'));if(cards.length){cards[heroIx%cards.length].classList.add('live');heroIx++}},1200);

const lenses={identity:[['LEGAL NAME','Amir Rahman','KYC + CRM'],['DOB','14 Mar 1988','KYC verified'],['ADDRESS','17 Queensway, London','2 active sources'],['PHONE','+44 •••• 7812','CRM + payment'],['EMAIL','amir.r••@mail.com','CRM'],['CUSTOMER SINCE','2019','Onboarding']],accounts:[['CURRENT ACCOUNT','••4821','Primary · active'],['BUSINESS ACCOUNT','••1094','Linked company'],['CARD','••7718','Consumer credit'],['WALLET','WLT-0921','Observed in payments'],['PRODUCTS','4','Across 2 relationships'],['BENEFICIARIES','11','3 recently added']],risk:[['CUSTOMER RISK','Elevated','Behavior + network'],['KYC STATUS','Current','Reviewed 12 Jun'],['PEP','No direct match','Screening'],['SANCTIONS','No direct match','Screening'],['BEHAVIOR','Rapid movement','Current signal'],['NETWORK RISK','Elevated','Shared infrastructure']],alerts:[['OPEN ALERTS','2','Fraud + AML'],['INVESTIGATION','INV-20481','Active'],['PRIOR CASE','INV-18942','Closed · no filing'],['APP SIGNAL','USD 8,450','Current'],['WIRE SIGNAL','USD 74,200','Linked network'],['OWNER','J. Morgan','Financial Crime Ops']],relationships:[['SHARED DEVICE','DEV-8841','High confidence'],['COMPANY','Meridian Exports Ltd','Director link'],['ADDRESS','17 Queensway','Shared with entity'],['BENEFICIARY','Gulf Star Trading','2-hop path'],['ACCOUNT LINK','••1094','Observed'],['EVIDENCE','16 observations','5 source systems']],history:[['ADDRESS CHANGE','03 Aug','CRM'],['DEVICE FIRST SEEN','29 Jul','Payments'],['BENEFICIARY ADDED','27 Jul','Payments'],['KYC REVIEW','12 Jun','CDD'],['COMPANY LINK','04 May','Registry'],['FIRST OBSERVED','18 Feb 2019','Onboarding']]};
function renderLens(k){entityBody.innerHTML=`<div class="entity-grid">${lenses[k].map(x=>`<div class="entity-fact"><small>${x[0]}</small><b>${x[1]}</b><span>${x[2]}</span></div>`).join('')}</div>`}renderLens('identity');document.querySelectorAll('.lens').forEach(b=>b.onclick=()=>{document.querySelectorAll('.lens').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderLens(b.dataset.lens)});
const sourceCopy={KYC:'Customer onboarding · verified identity fields · source KYC-UK-0182 · observed 2019 · refreshed Jun 2026. Evidence type: source-backed.',CRM:'Customer profile · phone/email/address · source CRM-44081 · last changed Aug 2026. Evidence type: source-backed.',PAYMENTS:'Account and transaction identity · source PAY-ACCT-4821 · ongoing observations. Evidence type: observed transaction data.',SCREENING:'Name, DOB and jurisdiction screening · source SCR-22018 · current review. Evidence type: screening result.',CASE:'Investigation evidence · alias, device and beneficiary observations · INV-20481. Evidence type: investigator evidence.',REGISTRY:'External company registry · director relationship to Meridian Exports Ltd · observed May 2026. Evidence type: external registry.'};document.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-source]').forEach(x=>x.classList.remove('active'));b.classList.add('active');sourceInspector.textContent=sourceCopy[b.dataset.source]});

const baseNodes=[['amir','Amir Rahman','person',47,44,76],['acct1','Acct •4821','account risk',24,30,58],['device','DEV-8841','device risk',65,27,56],['company','Meridian Exports','company',72,58,74],['address','17 Queensway','address',28,67,56],['victim','APP Victim','person',7,18,52],['wire','Wire •2207','transaction',87,33,54],['gulf','Gulf Star Trading','company risk',87,73,72],['phone','Phone •7812','device',48,76,48],['acct2','Acct •1094','account',57,12,52],['benef','Beneficiary','person',13,78,50],['merchant','Merchant PSP','company',76,10,60]];
const extraNodes=[['wallet','Wallet 0921','account',37,14,48],['director','S. Qureshi','person',94,53,50],['shell','Orion Holdings','company risk',72,84,64],['bank','Correspondent','company',93,13,60],['email','Email match','device',37,88,46],['alert1','Fraud alert','alert risk',12,48,48],['alert2','AML alert','alert risk',92,90,48],['counter','Counterparty','person',4,61,50],['trust','Harbour Trust','company',60,91,60],['acct3','Acct •7740','account',18,8,48],['device2','DEV-2290','device',81,48,46],['wire2','Wire •3388','transaction',67,5,46],['addr2','Dubai address','address',95,67,52],['owner','Beneficial owner','person risk',52,4,54],['psp','Cross-border PSP','company',5,91,56],['phone2','Phone •2201','device',33,52,46],['wallet2','Wallet 774','account',83,22,46],['company2','Northstar LLC','company',41,6,58],['acct4','Acct •9012','account',6,35,46],['txn3','Card txn','transaction',54,88,44],['case1','INV-20481','investigation',20,92,50],['case2','Prior case','investigation',97,42,48]];
let expanded=false,pathMode=false,currentFilter='ALL';const pathIds=['victim','acct1','device','amir','wire','gulf'];function graphNodes(){return expanded?baseNodes.concat(extraNodes):baseNodes}
const typeOf=n=>n[2].split(' ')[0];
function renderGraph(){let ns=graphNodes(),html='',edges=[];ns.forEach((n,i)=>{if(i){let parent=ns[Math.max(0,(i-1)%Math.min(i,6))];edges.push([parent[0],n[0]])}});edges.push(['victim','acct1'],['acct1','device'],['device','amir'],['amir','wire'],['wire','gulf'],['amir','company'],['company','gulf'],['amir','phone']);if(expanded){edges.push(['company','shell'],['shell','owner'],['gulf','director'],['wire','bank'],['device','device2'],['acct2','wallet'],['company2','owner'],['alert1','acct1'],['alert2','gulf'],['case1','amir'])}function node(id){return ns.find(n=>n[0]===id)}edges.forEach(e=>{let a=node(e[0]),b=node(e[1]);if(!a||!b)return;let dx=b[3]-a[3],dy=b[4]-a[4],len=Math.sqrt(dx*dx+dy*dy),ang=Math.atan2(dy,dx)*180/Math.PI,isPath=pathIds.includes(e[0])&&pathIds.includes(e[1]);html+=`<i class="g-edge ${pathMode?(isPath?'path':'dim'):''}" style="left:${a[3]}%;top:${a[4]}%;width:${len}%;transform:rotate(${ang}deg)" data-edge="${e[0]}|${e[1]}"></i>`});ns.forEach(n=>{let onPath=pathIds.includes(n[0]),hidden=currentFilter!=='ALL'&&!typeOf(n).startsWith(currentFilter.toLowerCase().slice(0,-1));html+=`<button class="g-node ${n[2]} ${pathMode?(onPath?'path':'dim'):''} ${hidden?'hidden':''}" style="left:calc(${n[3]}% - ${n[5]/2}px);top:calc(${n[4]}% - ${n[5]/2}px);width:${n[5]}px;height:${n[5]}px" data-node="${n[0]}">${n[1]}</button>`});graph.innerHTML=html;graph.querySelectorAll('[data-node]').forEach(b=>b.onclick=()=>{graph.querySelectorAll('.g-node').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');inspectNode(b.dataset.node)});graph.querySelectorAll('[data-edge]').forEach(b=>b.onclick=()=>inspectEdge(b.dataset.edge));if(pathMode)animatePath()}
function inspectNode(id){let n=graphNodes().find(x=>x[0]===id);graphInspector.innerHTML=`<div class="eyebrow">NETWORK INSPECTOR</div><h3>${n[1]}</h3><span class="inspect-badge">${typeOf(n).toUpperCase()}</span><span class="inspect-badge">${n[2].includes('risk')?'RISK RELEVANT':'OBSERVED'}</span><div class="inspect-row"><small>PROVENANCE</small><b>Source-backed observations</b></div><div class="inspect-row"><small>CONFIDENCE</small><b>${n[2].includes('risk')?'HIGH · risk relevant':'OBSERVED'}</b></div><div class="inspect-row"><small>WHY IT MATTERS</small><b>Connected to the active investigation context.</b></div><div class="graph-stats"><div><small>EDGES</small><b>${Math.floor(Math.random()*5)+2}</b></div><div><small>SOURCES</small><b>${Math.floor(Math.random()*3)+2}</b></div><div><small>FIRST SEEN</small><b>29 Jul</b></div><div><small>LAST SEEN</small><b>20 Aug</b></div></div>`}
function inspectEdge(v){let [a,b]=v.split('|');graphInspector.innerHTML=`<div class="eyebrow">RELATIONSHIP EVIDENCE</div><h3>${a} → ${b}</h3><div class="inspect-row"><small>RELATIONSHIP</small><b>Observed / derived connection</b></div><div class="inspect-row"><small>DIRECTION</small><b>${a} → ${b}</b></div><div class="inspect-row"><small>EVIDENCE</small><b>2 supporting observations</b></div><div class="inspect-row"><small>SOURCE</small><b>Payments + investigation evidence</b></div><div class="inspect-row"><small>CONFIDENCE</small><b>High</b></div><div class="inspect-row"><small>FIRST / LAST OBSERVED</small><b>29 Jul / 20 Aug 2026</b></div><div class="inspect-row"><small>WHY IT MATTERS</small><b>Contributes to the suspicious path linking otherwise separate signals.</b></div>`}
function animatePath(){const ns=graphNodes();let pts=pathIds.map(id=>ns.find(n=>n[0]===id)).filter(Boolean);if(!pts.length)return;let token=document.createElement('i');token.className='path-token';graph.appendChild(token);let i=0;function step(){if(!token.isConnected)return;let p=pts[i%pts.length];token.style.left=`calc(${p[3]}% - 4px)`;token.style.top=`calc(${p[4]}% - 4px)`;i++;if(i<=pts.length)setTimeout(step,600);else setTimeout(()=>token.remove(),900)}step()}
renderGraph();expandGraph.onclick=()=>{expanded=true;renderGraph()};pathGraph.onclick=()=>{pathMode=!pathMode;pathGraph.textContent=pathMode?'Show full network':'Show suspicious path';renderGraph()};resetGraph.onclick=()=>{expanded=false;pathMode=false;currentFilter='ALL';pathGraph.textContent='Show suspicious path';document.querySelectorAll('.filter').forEach((x,i)=>x.classList.toggle('active',i===0));renderGraph();graphInspector.innerHTML='<div class="eyebrow">NETWORK INSPECTOR</div><h3>Select an object</h3><p>Explore a node or relationship to inspect evidence, provenance, confidence and why it matters.</p>'};
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{currentFilter=b.textContent.trim();document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderGraph()});