const domainRoutes={aml:'aml.html',kyc:'kyc.html',rtm:'rtm.html',fraud:'fraud.html',framl:'framl.html',sanctions:'sanctions.html',invest:'investigation.html',report:'regulatory-reporting.html'};
const reduceMotion=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
document.querySelectorAll('.coverage article').forEach(card=>{const key=[...card.classList].find(c=>domainRoutes[c]);if(key&&card.parentElement?.tagName==='A')card.parentElement.href=domainRoutes[key];if(!reduceMotion){card.addEventListener('mousemove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(700px) rotateX(${y*-2}deg) rotateY(${x*2}deg) translateY(-4px)`});card.addEventListener('mouseleave',()=>card.style.transform='')}});
// Route the operating chain to the dedicated product experiences rather than collapsing AI/governance into Investigations.
document.querySelectorAll('.operating a').forEach(a=>{const label=a.textContent.toUpperCase();if(label.includes('REASON'))a.href='agentic-ai.html';if(label.includes('GOVERN'))a.href='governance.html'});
const path=document.querySelectorAll('.path line');let p=0;if(!reduceMotion&&path.length)setInterval(()=>{path.forEach((x,i)=>{x.style.opacity=i<=p?1:.14});p=(p+1)%path.length},650);
const sections=[...document.querySelectorAll('section')];if('IntersectionObserver'in window){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('inview')}),{threshold:.08});sections.forEach(s=>io.observe(s))}else sections.forEach(s=>s.classList.add('inview'));
const heroChain=[...document.querySelectorAll('.livechain span,.livechain strong')];let hi=0;if(!reduceMotion&&heroChain.length)setInterval(()=>{heroChain.forEach(x=>x.style.textShadow='none');heroChain[hi%heroChain.length].style.textShadow='0 0 16px rgba(224,196,142,.8)';hi++},900);
const layers=[...document.querySelectorAll('.layers article')];let li=0;if(!reduceMotion&&layers.length)setInterval(()=>{layers.forEach(x=>x.classList.remove('layer-live'));layers[li%layers.length].classList.add('layer-live');li++},1500);
const style=document.createElement('style');style.textContent=`section{transition:opacity .6s ease,transform .6s ease}section:not(.inview){opacity:.94}.coverage article{transition:transform .18s ease,box-shadow .18s ease}.coverage article:hover{box-shadow:0 18px 45px rgba(17,23,34,.13)}.signature>a{transition:border-color .25s,transform .25s}.signature>a:hover{border-color:#566982;transform:translateY(-2px)}.operating div{transition:.2s}.operating div:hover{border-color:#8b7449;background:#101a29}.editorial article{transition:transform .2s}.editorial article:hover{transform:translateY(-3px)}.layers article{transition:background .35s,border-color .35s}.layers article.layer-live{background:linear-gradient(180deg,rgba(121,199,200,.055),rgba(199,161,90,.025));box-shadow:inset 0 -1px 0 rgba(224,196,142,.12)}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important}}`;document.head.appendChild(style);